Htt 9 4 11 cand1 v1
cbernet/cmgtools-lite pull request #56
Opened 2019-01-11 15:58 UTC by GaelTouquet

updates:
- MET v2
- Embedding
- minor sync updates (JEC, TES propagation, TauID called pre-TES)
- crab submitting minor updates
- got rid of some old sizeable files to be able to submit crab jobs using the latest JEC files

2019-01-11 16:39 UTC, cbernet requested changes

2019-01-11 16:39 UTC, cbernet commented on H2TauTau/python/heppy/analyzers/JetAnalyzer.py
> +        pt_cut = 50.0
in the configuration of the analyzer, the user should provide a lambda
```
is_badjet = lambda ....
```

2019-01-11 16:39 UTC, cbernet commented on H2TauTau/python/heppy/analyzers/JetAnalyzer.py
> +            if ( hjet.correctedJet("Uncorrected").pt() > pt_cut or abs(hjet.eta()) < eta_min or abs(hjet.eta()) > eta_max ) :
use the lambda directly

2019-01-11 16:39 UTC, cbernet commented on H2TauTau/python/heppy/analyzers/METAnalyzer.py
> +        for N in range(ptc.numberOfDaughters()):
avoid single letter variables, except for i, j in enumeration. 
don't use single capital variables. 
here ndau would be good

2019-01-11 16:39 UTC, cbernet commented on H2TauTau/python/heppy/analyzers/METAnalyzer.py
> +
rm line

2019-01-11 16:39 UTC, cbernet commented on H2TauTau/python/heppy/analyzers/METAnalyzer.py
> +
rm line

2019-01-11 16:39 UTC, cbernet commented on H2TauTau/python/heppy/analyzers/NtupleProducer.py
> +                    print varname, 'took the wrong type'
clarify error message

2019-01-11 16:39 UTC, cbernet commented on H2TauTau/python/heppy/analyzers/TauP4Scaler.py
> +            tau.tauID('byIsolationMVArun2017v2DBoldDMwLTraw2017')
add a comment before these two lines
explain in the gitlab

2019-01-11 16:39 UTC, cbernet commented on H2TauTau/python/heppy/ntuple/ntuple_variables.py
> +    n_pu = v(lambda x: getattr(x, 'nPU', default) if getattr(x, 'nPU', default) is not None else default, int),
add comments for all these changes (at least write that you cover specificities of the embedded samples )

2019-01-11 16:39 UTC, cbernet commented on H2TauTau/python/heppy/ntuple/ntuple_variables.py
> +    event_flags[flag] = v(lambda x: getattr(x,flag,1), int)
and here explain why chosing 1 (no flag is good )

2019-01-11 16:39 UTC, cbernet commented on H2TauTau/python/heppy/sequence/common.py
> +    filter_func = lambda x : x.pt()>20 and abs(x.eta())<4.7 and x.jetID("POG_PFID_Tight") and not ( x.pt() < 50 and abs(x.eta()) > 2.65 and abs(x.eta()) < 3.139 )
line too long, break it \

2019-01-14 10:08 UTC, GaelTouquet commented
requested changes have been added

2019-01-14 14:14 UTC, cbernet commented on H2TauTau/python/heppy/analyzers/NtupleProducer.py
> +                    message = ' '.join(['Variable',
please use format

2019-01-14 14:20 UTC, GaelTouquet commented on H2TauTau/python/heppy/analyzers/NtupleProducer.py
> +                    message = ' '.join(['Variable',
Done

2019-01-14 14:34 UTC, merged